apiVersion: cloudstate.io/v1alpha1
kind: StatefulStore
metadata:
  name: inmemory
spec:
  inMemory: true
---
apiVersion: cloudstate.io/v1alpha1
kind: StatefulService
metadata:
  name: credit
spec:
  storeConfig:
    statefulStore:
      name: inmemory
  containers:
  - image: gcr.io/sap-nj-serverless-poc/credit:latest
    name: user-function
    env:
    - name: HOST
      value: localhost
    - name: PORT
      value: "8080"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
